import json

import requests

url = 'http://127.0.0.1:38081/score'

data = [
    [['Amandine Descat', 'Amandine Descat'], [2017, 2018],
     ['Journal of The International Society of Sports Nutrition', 'PLOS ONE'], [
         'Center of measurements and analysis (CMA), Facultyof Pharmaceutical Sciences, Université de Lille, Lille, France',
         ''], [
         'Acute cocoa Flavanols intake has minimal effects on exercise-induced oxidative stress and nitric oxide production in healthy cyclists : a randomized controlled trial Background Cocoa flavanols (CF) can stimulate vasodilation by improved nitric oxide (NO) synthesis and have antioxidant and anti-inflammatory capacities. This study aimed to examine whether acute CF intake can affect exercise-induced changes in antioxidant capacity, oxidative stress, inflammation and NO production, as well as exercise performance and recovery in well-trained cyclists.',
         'A pharmaco-metabolomics approach in a clinical trial of ALS: Identification of predictive markers of progression ']],
    [['Abigail Taylor', 'Abi Lane'], [2019, 2004], ['Veterinary Surgery', 'Applied Animal Behaviour Science'],
     ['', 'Department of Clinical Veterinary Medicine, University of Cambridge, Cambridge, UK'],
     ['Effect of a mindfulness exercise on stress in veterinary students performing surgery ',
      'A note on behavioural laterality in neonatal lambs In some mammals behavioural laterality is influenced by the perinatal environment, through stress effects on brain lateralisation, and by gender through variation in testosterone secretion. Therefore, a study was conducted on 54 neonatal lambs to determine whether laterality existed at birth and whether litter size, which would be expected to relate to perinatal stress, or gender influenced laterality of locomotor, tail movement and lying behaviours. The lambs exhibited a normal distribution of laterality when: (1) stepping forward from a standing position, (2) lying, and (3) initial movements of the tail when suckling, during the first 24 h after birth. The gender of the individual and number of siblings had no effect on laterality in these behaviours.']],
    [['Philip J. Cash', 'Phillip Cash'], [2013, 2015], ['Design Studies', 'Journal of Engineering Design'], [
        'Department of Management Engineering, Technical University of Denmark, Building 426, Room 122, DK-2800 Lyngby, Denmark',
        'Department of Management Engineering, DTU Technical University of Denmark, Produktionstorvet, Building 424, room 122, 2800 Kgs. Lyngby, Denmark'],
     [
         'A comparison of designer activity using core design situations in the laboratory and practice In 2011 one quarter of all articles published in Design Studies and the Journal of Engineering Design used experimental studies. However, there is little work exploring the relationship between laboratory and practice. This paper addresses this by detailing an analysis of designer activity in three situations commonly studied by design researchers: information seeking, ideation and design review. This comparison is instantiated through three complementary studies: an observational study of practice and two experimental studies. These reveal a range of similarities and differences that are described using a mixed methods approach. Based on this it is concluded that laboratory studies are important research tools and that clear and definable relationships do exist between design activity in practice and the laboratory.',
         'Multifaceted assessment of ideation: using networks to link ideation and design activity Ideation is core to the innovation process, and has been the subject of study across a range of fields, from psychology to engineering. However, despite substantial progress in outcome-based descriptions of idea generation, research has often resulted in more questions than answers. For example, open questions remain with respect to the differences in behaviour related to ideation between novices and experts, the change in rates of ideation over time in different design teams, and the changing role of ideation from conceptual to detailed design. In each of these cases, robust explanation has proved elusive due to difficulties in characterising the ideation process itself. This paper discusses a major new approach for elucidating ideation and its related design processes through direct observation. A novel network visualisation approach is demonstrated in practice for the first time. This uses network analysis to link ideas dynamically to both the engineering context and the wider design process. This link...']],
    [['Masashi Ishikawa', 'Masashi Ishikawa'], [2016, 2019],
     ['Advanced Composite Materials', 'Journal of Clinical Monitoring and Computing'], [
         'Department of Materials Science and Technology, Tokyo University of Science, 6-3-1 Niijuku, Katsushika-ku, Tokyo, 125-8585, Japan',
         ''], [
         'Time-dependent deformation of ROHACELL-core CFRP sandwich panels In this study, we experimentally and analytically investigated time-dependent deformation of carbon-fiber reinforced plastic sandwich panels with three kinds of polymer foam-core ROHACELL, with the deformation caused by moisture absorption. Tensile tests for the ROHACELLs before and after moisture absorption were performed using the digital image correlation method, and we obtained a stress&#x2013;strain relationship for each condition. Surface deformations of sandwich panels were calculated using finite element analyses to examine the elasto-plastic deformation of the ROHACELLs based on the tensile test results. Experimentally measured deformation in the sandwich panels varied depending on the cell size of cores, and the largest measured deformation after the moisture absorption was approximately 100&#x00A0;&#x03BC;m. This was much larger than the analytical result. On the basis of this study, we suggest that the main reason for the deformation may be an irreversible shrinkage of the ROHACELLs caused the absorption of moistu...',
         'Postoperative desaturation and bradypnea after general anesthesia in non-ICU patients: a retrospective evaluation ']],
    [['M. Cortina-Borja', 'Mario Cortina-Borja'], [2017, 2016], ['', 'Public Health Nutrition'],
     ['', 'University College London'], [
         '[Accepted Manuscript] A scaling approach to record linkage. With increasing availability of large datasets derived from administrative and other sources, there is an increasing demand for the successful linking of these to provide rich sources of data for further analysis. Variation in the quality of identifiers used to carry out linkage means that existing approaches are often based upon &#039;probabilistic&#039; models, which are based on a number of assumptions, and can make heavy computational demands. In this paper, we suggest a new approach to classifying record pairs in linkage, based upon weights (scores) derived using a scaling algorithm. The proposed method does not rely on training data, is computationally fast, requires only moderate amounts of storage and has intuitive appeal. Copyright &#x00A9; 2017 John Wiley &amp; Sons, Ltd.',
         'Development and validation of a photographic food atlas for portion size assessment in the southern plains of Nepal OBJECTIVE: To develop and validate a photographic food atlas of common foods for dietary assessment in southern Nepal. DESIGN: We created a life-sized photographic atlas of forty locally prepared foods. Between March and June 2014, data collectors weighed portion sizes that respondents consumed during one mealtime and then a different data collector revisited the household the next day to record respondents&#039; estimations of their previous day&#039;s intakes using the atlas. Validity was assessed by percentage error, Cohen&#039;s weighted kappa (&#x03BA; w) and Bland-Altman limits of agreement. SETTING: Dhanusha and Mahottari districts in southern Nepal. SUBJECTS: A random sample of ninety-five adults in forty-eight rural households with a pregnant woman. RESULTS: Overall, respondents underestimated their intakes (mean error =-4&#x00B7;5 %). Rice and dal (spiced lentil soup) intakes were underestimated (-14&#x00B7;1 % and -34&#x00B7;5 %, respectively), but vegetable curry intake was overestimated (+20&#x00B7;8 %). Rice and vegetable curry portion size images were significantly reliably selected (Cohen&#039;s &#x03BA; w (se): rice=0&#x00B7;391 (0&#x00B7;105); vegetable curry=0&#x00B7;430 (0&#x00B7;139)), whereas dal images were not. Energy intake over one mealtime was under-reported by an average of 569 kJ (136 kcal; 4&#x00B7;5 % error) using recall compared with the weighing method. CONCLUSIONS: The photographic atlas is a useful tool for field estimation of dietary intake. Average errors were low, and there was &#039;modest&#039; agreement between weighed and recalled portion size image selection of rice and vegetable curry food items. Error in energy estimation was low but with wide limits of agreement, suggesting that there is scope for future work to reduce error further.']],
    [['Guanlun Guo', 'Guanlun Guo'], [2017, 2016],
     ['Canadian Journal of Chemistry', 'Journal of International Medical Research'], ['',
                                                                                      '2Hubei Key Laboratory of Advanced Technology of Automotive Components, School of Automotive Engineering, Wuhan University of Technology, Wuhan, China'],
     [
         'Naphthalene formation pathways from phenyl radical via vinyl radical (C2H3) and vinylacetylene (C4H4): computational studies on reaction mechanisms and kinetics The reaction mechanisms of PAH formation from phenyl radical (C6H5) to naphthalene via C2H3 (C2H3-Path) and C4H4 (C4H4-Path) were investigated by the G3(MP2, CC) method. The hydrogen abstraction, ring closure, cis&#x2013;trans isomerization, and disproportionation reactions were considered, as well as their occurred sequence. The results showed that H-abstraction reactions occurred more easily than H-dissociation reactions. The cis&#x2013;trans conversion reactions in sub-routes of C2H3-Path and C4H4-Path provided the largest barriers of 51, 53, and 36 kcal/mol along their routes, which illustrated that the cis&#x2013;trans isomerization was energetically costly in the PAH formation process. The entrance barriers of C2H2-Path, C2H3-Path, and C4H4-Path are 6, 8, and 3 kcal/mol, respectively, which indicates that it is easier to add C4H4 to C6H5 compared with adding C2H2 to C2H3. C2H3 additions were highly exothermic with reaction energies greater than 110 kcal/mol, and compared with C2H2 additions, C2H3 additions were irrevers...',
         'Genetic polymorphisms associated with heart failure: A literature review ObjectiveTo review possible associations reported between genetic variants and the risk, therapeutic response and prognosis of heart failure.MethodsElectronic databases (PubMed, Web of Science and CNKI) were systematically searched for relevant papers, published between January 1995 and February 2015.ResultsEighty-two articles covering 29 genes and 39 polymorphisms were identified.ConclusionGenetic association studies of heart failure have been highly controversial. There may be interaction or synergism of several genetic variants that together result in the ultimate pathological phenotype for heart failure.']],
    [['Hélder Daniel Silva', 'Hélder Vinicius Carneiro da Silva'], [2012, 2019],
     ['Food and Bioprocess Technology', 'Journal of Enzyme Inhibition and Medicinal Chemistry'],
     ['University of Minho', 'Departamento de Antibióticos, Universidade Federal de Pernambuco, Recife, PE, Brazil; '],
     [
         'Nanoemulsions for Food Applications: Development and Characterization The application of nanotechnology to food, medical and pharmaceutical industries has received great attention from the scientific community. Driven by the increasing consumers&#x2019; demand for healthier and safer food products and the need for edible systems able to encapsulate, protect, and release functional compounds, researchers are currently focusing their efforts in nanotechnology to address issues relevant to food and nutrition. Nanoemulsion technology is particularly suited for the fabrication of encapsulating systems for functional compounds as it prevents their degradation and improves their bioavailability. This review focuses on nanoemulsions and provides an overview of the production methods, materials used (solvents, emulsifiers, and functional ingredients) and of the current analytical techniques that can be used for the identification and characterization of nanoemulsions. Finally, nanotechnological applications in foods currently marketed are reported.',
         'Synthesis and biological evaluation of thiazole derivatives as LbSOD inhibitors ']],
    [['L. Arnoldi', 'L. Arnoldi'], [2014, 2015], ['Nano Letters', 'Ultramicroscopy'], ['',
                                                                                       'GPM UMR 6634, Université de Rouen, Avenue de l\'Université, 76801, BP12, 76801 Saint Etienne du Rouvray, France'],
     [
         'Do Dielectric Nanostructures Turn Metallic in High-Electric dc Fields? Three-dimensional dielectric nanostructures have been analyzed using field ion microscopy (FIM) to study the electric dc field penetration inside these structures. The field is proved to be screened within a few nanometers as theoretically calculated taking into account the high-field impact ionization process. Moreover, the strong dc field of the order of 0.1 V/A at the surface inside a dielectric nanostructure modifies its band structure leading to a strong band gap shrinkage and thus to a strong metal-like optical absorption near the surface. This metal-like behavior was theoretically predicted using first-principle calculations and experimentally proved using laser-assisted atom probe tomography (APT). This work opens up interesting perspectives for the study of the performance of all field-effect nanodevices, such as nanotransistor or super capacitor, and for the understanding of the physical mechanisms of field evaporation of dielectric nanotips in APT.',
         'Role of the resistivity of insulating field emitters on the energy of field-ionised and field-evaporated atoms Abstract In order to improve the accuracy of laser atom probe analyses, it is important to understand all the physical processes induced by the combination of the high electrical field and the femtosecond laser beam during field evaporation. New information can be accessed from the energy of evaporated surface atoms or field-ionised atoms of an imaging gas. In order to study the ions energy, we combine La-APT and FIM analyses in a new experimental setup equipped with electrostatic lenses. We report measurements for semiconductors and oxides and we study the influence of the illumination conditions (laser power and wavelength), the evaporation rate, the sample geometry and the tip preparation processes. The results are discussed taking into account the resistive properties of non-metallic samples and the photo-stimulated conductivity. This work clarifies the role of the laser and DC field in the energy deficit of field evaporated ions.']],
    [['Han-Ching Huang', 'H. C. Huang'], [2017, 2013],
     ['International journal of economics and finance', 'Applied Economics'],
     ['', 'Department of Finance , Chung Yuan Christian University , Chung Li , Taiwan '], [
         'Insider Trading and the Classification of Seasoned Equity Offerings: Evidence from Taiwan This paper investigates whether insider purchasing or selling before Season equity offerings (SEO) announcement have the impact on the cumulative abnormal returns (CAR) around SEO announcement in Taiwan. We find that there are negative announcement effects around the SEO announcement, which is not consistent with the argument that there are usually positive announcement effects around the SEO announcement in Taiwan. Moreover, long-run abnormal returns following SEOs are negative. Therefore, the motivation of SEO has changed from investment to overvaluation.. Although there is net buying prior to SEO announcement, the outside investors still regard SEO announcement as a signal of overvaluation instead of growth potential.',
         'Does option provide more informative content than stock after regulation fair disclosure This article examines the impact of Regulation Fair Disclosure (Reg FD), which intends to eliminate selective disclosure to only a few privileged interested parties, on the information embedded in the stock-and-option markets prior to tender offer announcements. In the pre-announcement period after Reg FD, the volume of public option information contains less information about subsequent stock price movements. Although the quantity of public information may be higher after Reg FD, the inferior quality of publicly available option information dominates the higher quantity. Thus, the predictive power of option information decreases. In the post-RFD pre-announcement period, the volume of public option information is more informative than the volume of stock private information. It indicates that although the quality of private stock information is superior to that of public option information, the much lower quantity of stock information results in a lower predictive power of private stock information than that of public option information.']],
    [['Kibog Park', 'Kibog Park'], [2017, 2012], ['Current Applied Physics', 'ACS Applied Materials & Interfaces'], [
        'School of Electrical and Computer Engineering, Ulsan National Institute of Science and Technology (UNIST), Ulsan, 44919, Republic of Korea',
        ''], [
         'Formation of graphene on amorphous SiC film by surface-confined heating with electron beam irradiation Abstract It is demonstrated experimentally that graphene can form on the surface of an amorphous SiC film by irradiating electron beam (e-beam) at low acceleration voltage. As the electron irradiation fluency increases, the crystallinity and uniformity of graphene improve, which is confirmed by the changes of the measured Raman spectra and secondary electron microscopy images. Due to the shallow penetration depth of e-beam with low acceleration voltage, only the region near the surface of SiC film will be heated by the thermalization of irradiated electrons with multiple scattering processes. The thermalized electrons are expected to weaken the bond strength between Si and C atoms so that the thermal agitation required for triggering the sublimation of Si atoms decreases. With these assistances of irradiated electrons, it is considered that graphene can grow on the surface of SiC film at temperature reduced substantially in comparison with the conventional vacuum annealing process.',
         'Facile Synthesis of Few-Layer Graphene with a Controllable Thickness Using Rapid Thermal Annealing Few-layer graphene films with a controllable thickness were grown on a nickel surface by rapid thermal annealing (RTA) under vacuum. The instability of nickel films in air facilitates the spontaneous formation of ultrathin (&lt;2&#x2013;3 nm) carbon- and oxygen-containing compounds on a nickel surface; thus, the high-temperature annealing of the nickel samples without the introduction of intentional carbon-containing precursors results in the formation of graphene films. From annealing temperature and ambient studies during RTA, it was found that the evaporation of oxygen atoms from the surface is the dominant factor affecting the formation of graphene films. The thickness of the graphene layers is strongly dependent on the RTA temperature and time, and the resulting films have a limited thickness (&lt;2 nm), even for an extended RTA time. The transferred films have a low sheet resistance of &#x223C;0.9 &#x00B1; 0.4 k&#x03A9;/sq, with &#x223C;94% &#x00B1; 2% optical transparency, making them useful for applications as flexible transparent conductors.']]

]

data = json.dumps(data)
print(data)
ret = requests.post(url, data={"metadata": data})
print()
print(json.dumps(json.loads(str(ret.text)), indent=4))
